# Generated by Django 3.1.7 on 2021-03-30 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('central', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exemplos',
            name='arquivo',
            field=models.FileField(null=True, upload_to=None),
        ),
        migrations.AlterField(
            model_name='exemplos',
            name='imagem',
            field=models.ImageField(null=True, upload_to=None),
        ),
    ]
