# Generated by Django 3.1.7 on 2021-03-30 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('central', '0002_auto_20210330_1917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exemplos',
            name='arquivo',
            field=models.FileField(blank=True, upload_to='arquivos/'),
        ),
        migrations.AlterField(
            model_name='exemplos',
            name='imagem',
            field=models.ImageField(blank=True, upload_to='imagens/'),
        ),
    ]
