# Generated by Django 3.1.7 on 2021-04-03 20:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('central', '0003_auto_20210330_2040'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Exemplos',
            new_name='Exemplo',
        ),
        migrations.CreateModel(
            name='CamposRelacionado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criados', models.DateField(verbose_name='Criação')),
                ('modificado', models.DateField(auto_now=True, verbose_name='Atualização')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo?')),
                ('chave_estrangeira', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='CamposRelacionado1', related_query_name='CamposRelacionado11', to='central.exemplo')),
                ('chave_estrangeira_self', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='CamposRelacionado2', related_query_name='CamposRelacionado2', to='central.camposrelacionado')),
                ('muitos_para_muitos', models.ManyToManyField(to='central.Exemplo')),
                ('muitos_para_muitos_self', models.ManyToManyField(blank=True, null=True, related_name='_camposrelacionado_muitos_para_muitos_self_+', to='central.CamposRelacionado')),
                ('um_para_um', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='CamposRelacionado3', related_query_name='CamposRelacionado3', to='central.exemplo')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
